export const list = [
    { id: 1, name: "Boat riding" },
    { id: 2, name: "Horseback Riding" },
    { id: 3, name: "Rafting" },
    { id: 4, name: "Paragliding" },
    { id: 5, name: "Hiking" },
    { id: 6, name: "Sightseeing" },
    { id: 7, name: "Quad biking" },
    { id: 8, name: "Amusement Park" },
    { id: 9, name: "Wine Degustation" },
    { id: 10, name: "Honey" },
    { id: 11, name: "Antique Shopping" },
    { id: 12, name: "Cable Cars" },
    { id: 13, name: "Souvenir Shopping" },
    { id: 14, name: "Walking" },
    { id: 15, name: "Skiing" },
    { id: 16, name: "Religion" },
    { id: 17, name: "Museum" },
    { id: 18, name: "Stalining" },
    { id: 19, name: "Cave exploration" },
    // { id: 20, name: "Skiing" },
    { id: 21, name: "Jetskiing" },
    // { id: 22, name: "Walking" },
    { id: 23, name: "Yacht Tours" },
    { id: 24, name: "Swimming" },
    // { id: 25, name: "Religion (cross)" },
    // { id: 26, name: "Winetasting" },
    { id: 27, name: "Cable Bicycles" },
    { id: 28, name: "Giant swing" }
];


